### ISSUE TITLE
Update image on HPC

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/CompTASA#1]
Hi @MunyaMusvosvi, I updated the image to have all the packages your updated `UtilsAutoGating` package needs. Well, it's building now, but will be done in the next thirty minutes.

So, when it's done, you can pull it onto the hpc using the same code as the readme (that `apptainer-pull -o SATVILab` from within the `CompTASA` repo), and then go from tehre.

**Comment by MunyaMusvosvi** [comment]
Managed to pull the updated image onto the hpc. I had to use the following code though apptainer-pull -o SATVILab --force because comptasa.sif already existed
